// Package host installs project-local delivery assets. It does not interpret
// project records or alter any user-level host settings.
package host

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
)

type Config struct {
	Root, Binary, SourceRoot, SourceRepository string
	Codex                                      bool
}

const sourceRootRecovery = "rerun haft10 init --codex --root <selected-project-root> --source-root <existing-source-directory> for the selected project"

type Result struct {
	Root      string   `json:"root"`
	Created   []string `json:"created"`
	Updated   []string `json:"updated"`
	Unchanged []string `json:"unchanged"`
	// Unresolved contains every relevant path not yet published or rechecked.
	// Preflight has no completed paths, including those inspected before a conflict.
	Unresolved []string `json:"unresolved,omitempty"`
}
type planned struct {
	path          string
	before, after []byte
	exists        bool
}

// These are exact generated bytes from the accepted B1 base 3d3ad688. Only
// unchanged generated assets can advance; operator edits and unknown generated
// versions remain conflicts.
var b1GeneratedDigests = map[string]string{
	"AGENTS.md":                        "9fc10d6a28e7733e5c30c8e15ae9396a68789e437559664d99421a9f43ce49e8",
	".agents/skills/h-decide/SKILL.md": "128dadc6f5bf221a3c36da7745cae5faf04db613ff67d323a9df2162684d0afc",
	".agents/skills/h-reason/SKILL.md": "6ac79c7e842582b16ed86b16d87d4cc8496228fcefb4d3266cad57d14165b01b",
	".agents/skills/h-spec/SKILL.md":   "7b2ab5de20e33d2d579a0e5b2725b6fe31d735da255c7dde5edcef42a80a2371",
	".agents/skills/h-verify/SKILL.md": "6a6f48ed052b67a6c864cbe8cb65b3746a3e249e11017610ace318263c52a7c7",
}

// T01AR was accepted at dd93bd6e before the T01R capture guidance. Its
// unchanged generated assets are valid upgrade inputs, including on a stable
// project path where no MCP address changes.
var t01arGeneratedDigests = map[string]string{
	"AGENTS.md":                        "264f86a53fbce8207f2112faf2d5b75858d232442edaa95b50a5375ea8ed369e",
	".agents/skills/h-decide/SKILL.md": "fdd85806862661edf4d50bf1f18ab4ed499e8bdfaa775f2b3fc48281425114ef",
	".agents/skills/h-reason/SKILL.md": "f16301c8daeb097d620e979b1e4e160938cd6607e492bdce3003b490b84b981d",
	".agents/skills/h-spec/SKILL.md":   "7675ce04f2b9969bd89d74abcb707bea1188b8a7423b149e03d17dde2684238c",
	".agents/skills/h-verify/SKILL.md": "c7ade5f1baef9ca5d73fb09d7d717af6e5e6f40dac94ca5f85f44cbab45bcac7",
}

// T01R is the last generated host version before haft/2 spec authoring. Exact
// prior assets can advance to the new instructions while user edits remain
// protected by the same whole-file or managed-block preflight.
var t01rGeneratedDigests = map[string]string{
	"AGENTS.md":                        "8ecbaab711e219b5c3a4d21525f392bef6d0fd8ac666ff40425d272f8e5099f7",
	".agents/skills/h-decide/SKILL.md": "214e744b33d3a69bf346de9bfbeb8e51564cb960b7e5a2a778b195576f6ec158",
	".agents/skills/h-reason/SKILL.md": "304ac15f9f1e0bd86b3cb32954cb47d6a1c3c8b14a341beba70ceec6dd4a2808",
	".agents/skills/h-spec/SKILL.md":   "f091f6592f9508e1bc19e864a68d8dfa8881ec46aa6eb8a2e56f152709c421e1",
	".agents/skills/h-verify/SKILL.md": "39b2ca4cc40950eb4963910db11c03c898c44d3c60801c1b62daae91e3564541",
}

// T01B generated instructions precede the T01R2 capture and disclosure
// guidance. Only these exact bytes may advance automatically; a local edit
// remains a conflict.
var t01bGeneratedDigests = map[string]string{
	"AGENTS.md":                        "f064f059e406a7865b8397bd6bf9ff17c1d9e841841516d40e6f6c458b9fe2ac",
	".agents/skills/h-decide/SKILL.md": "499176538c31f72183ce16a5895c49ddcc2f72e4654d4379855a97594e317b7f",
	".agents/skills/h-reason/SKILL.md": "18df0863bb03f70546cff9a5c0deac287addfc275b539ffdc5e76697127d8419",
	".agents/skills/h-spec/SKILL.md":   "884a7d1aaa8a1672009a1f429c883bb3c4c190dff7917a556378e18dd0876231",
	".agents/skills/h-verify/SKILL.md": "debf0ea958abcd5dd33713caa4699809d1219c67cb8e8bfbf67ccbb31ebe46c2",
}

// These exact assets came from the integrated T01R2 handoff ad16e157 and the
// immediately preceding T01BR handoff c685c6dc. Version pins admit generated
// content only; an edited or unknown carrier still fails preflight.
var t01r2GeneratedDigests = map[string]string{
	"AGENTS.md":                        "ada752d8289434daa405f860468c6e0805ed09cb31a4bbf69bd4b59a389d502d",
	".agents/skills/h-decide/SKILL.md": "87da335d8db22507c07bf777dec37d0d167e727406747c1c478ce4843fbaa4d0",
	".agents/skills/h-reason/SKILL.md": "661a99894e8ef84641cdb563d4bdb0ae5763e98a175a67a65edabd0661a93808",
	".agents/skills/h-spec/SKILL.md":   "28434b053c3980be89249774afce2cebdd7fab736833721d618649a5cd2e740e",
	".agents/skills/h-verify/SKILL.md": "b2feab22da320d1b0967ab0a5ab8353c48f6c1f31a953268e069ceb6541c2410",
}

var t01brGeneratedDigests = map[string]string{
	"AGENTS.md":                        "4ca125e400380f2e5ef4b602e6236c796a374f445705550ca1980b047e2f083b",
	".agents/skills/h-decide/SKILL.md": "542097fafd217e5ceb867d5dd2fb82dbd5068126ee1dd6dcc325d1d7349adb58",
	".agents/skills/h-reason/SKILL.md": "7359648f73514cbc811d394993622d7f797d23065c24d883d55330681fc8c7e2",
	".agents/skills/h-spec/SKILL.md":   "615ed3765d03016de7cbce6e291ba1c7b5226e9fe7e6c6b26b15f52d5930bdb9",
	".agents/skills/h-verify/SKILL.md": "b0d373bd0b5ff220785a4d02ed99ea3d9480f89582d899269eb3b04e5e046f47",
}

var priorGeneratedDigests = []map[string]string{
	b1GeneratedDigests,
	t01arGeneratedDigests,
	t01rGeneratedDigests,
	t01bGeneratedDigests,
	t01r2GeneratedDigests,
	t01brGeneratedDigests,
}

func knownB1Generated(name string, raw []byte) bool {
	return generatedDigestMatches(b1GeneratedDigests, name, raw)
}

func generatedDigestMatches(digests map[string]string, name string, raw []byte) bool {
	want, ok := digests[name]
	if !ok {
		return false
	}
	actual := sha256.Sum256(raw)
	digest := hex.EncodeToString(actual[:])
	return digest == want
}

func knownPriorGenerated(name string, raw []byte) bool {
	return slices.ContainsFunc(priorGeneratedDigests, func(digests map[string]string) bool {
		return generatedDigestMatches(digests, name, raw)
	})
}

// Init preflights every destination before writing. Identical reruns are no-ops;
// exact known generated content can upgrade, while edited content is preserved.
func Init(c Config) (Result, error) {
	return initWithHooks(c, initHooks{})
}

type initHooks struct {
	beforePublish func(string) error
	afterPublish  func(string) error
}

func initWithHooks(c Config, hooks initHooks) (Result, error) {
	r := Result{Created: []string{}, Updated: []string{}, Unchanged: []string{}}
	files := map[string][]byte{"AGENTS.md": []byte(agents)}
	if c.Codex {
		files[".codex/config.toml"] = nil
		for name, body := range Skills() {
			files[".agents/skills/"+name+"/SKILL.md"] = []byte(body)
		}
	}
	names := make([]string, 0, len(files))
	for name := range files {
		names = append(names, name)
	}
	sort.Strings(names)
	r.Unresolved = slices.Clone(names)
	root, err := filepath.Abs(c.Root)
	if err != nil {
		return r, err
	}
	root, err = filepath.EvalSymlinks(root)
	if err != nil {
		return r, err
	}
	r.Root = root
	info, err := os.Stat(root)
	if err != nil || !info.IsDir() {
		return r, fmt.Errorf("project root must be an existing directory")
	}
	unlock, err := lockInitRoot(root)
	if err != nil {
		return r, err
	}
	defer unlock()
	blocks := map[string][2]string{"AGENTS.md": {"<!-- haft10:start -->", "<!-- haft10:end -->"}}
	if c.Codex {
		if !filepath.IsAbs(c.Binary) {
			return r, fmt.Errorf("candidate binary must be absolute")
		}
		bi, e := os.Stat(c.Binary)
		if e != nil || !bi.Mode().IsRegular() || bi.Mode()&0111 == 0 {
			return r, fmt.Errorf("candidate binary must be an existing executable")
		}
		c.Binary, e = filepath.EvalSymlinks(c.Binary)
		if e != nil {
			return r, fmt.Errorf("candidate binary is unavailable: %w", e)
		}
		if c.SourceRoot != "" {
			c.SourceRoot, e = filepath.Abs(c.SourceRoot)
			if e != nil {
				return r, fmt.Errorf("host_source_unavailable: %s; the selected source root cannot be resolved: %w", sourceRootRecovery, e)
			}
			c.SourceRoot, e = filepath.EvalSymlinks(c.SourceRoot)
			if e != nil {
				return r, fmt.Errorf("host_source_unavailable: %s; the selected source root is unavailable: %w", sourceRootRecovery, e)
			}
			sourceInfo, statErr := os.Stat(c.SourceRoot)
			if statErr != nil || !sourceInfo.IsDir() {
				return r, fmt.Errorf("host_source_unavailable: %s; the selected source root is not an existing directory. source %q", sourceRootRecovery, c.SourceRoot)
			}
		}
		installed := managedConfig{Root: root, Binary: c.Binary, SourceRoot: c.SourceRoot, SourceRepository: c.SourceRepository}
		files[".codex/config.toml"] = installed.block()
		blocks[".codex/config.toml"] = [2]string{configStart, configEnd}
	}
	var plan []planned
	for _, name := range names {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := safePath(root, path); err != nil {
			return r, fmt.Errorf("host_conflict: %s: %w", name, err)
		}
		before, err := os.ReadFile(path)
		exists := err == nil
		if err != nil && !os.IsNotExist(err) {
			return r, fmt.Errorf("host_conflict: %s: %w", name, err)
		}
		after := files[name]
		if marker, ok := blocks[name]; ok && exists {
			if name == "AGENTS.md" && bytes.Contains(before, []byte("<!-- haft:start -->")) {
				return r, fmt.Errorf("host_conflict: AGENTS.md already contains a different managed configuration")
			}
			if name == ".codex/config.toml" {
				after, err = mergeManagedConfig(before, managedConfig{Root: root, Binary: c.Binary, SourceRoot: c.SourceRoot, SourceRepository: c.SourceRepository})
			} else {
				after, err = mergeBlock(before, after, marker[0], marker[1], name)
			}
			if err != nil {
				return r, initPreflightError(name, err)
			}
		} else if exists && !bytes.Equal(before, after) && !knownPriorGenerated(name, before) {
			return r, fmt.Errorf("host_conflict: preserve existing %s", name)
		}
		plan = append(plan, planned{path: path, before: before, after: after, exists: exists})
	}
	for i, p := range plan {
		name, _ := filepath.Rel(root, p.path)
		name = filepath.ToSlash(name)
		if p.exists && bytes.Equal(p.before, p.after) {
			if err := verifyUnchangedInitFile(root, name, p); err != nil {
				return r, fmt.Errorf("host_conflict: %s: %w", name, err)
			}
			r.Unchanged = append(r.Unchanged, name)
			r.Unresolved = slices.Clone(names[i+1:])
			continue
		}
		if err := publishInitFile(root, name, p, hooks.beforePublish); err != nil {
			if strings.Contains(err.Error(), "host_conflict:") {
				return r, fmt.Errorf("host_conflict: %s: %w", name, err)
			}
			return r, fmt.Errorf("host_init: %s: %w", name, err)
		}
		if p.exists {
			r.Updated = append(r.Updated, name)
		} else {
			r.Created = append(r.Created, name)
		}
		r.Unresolved = slices.Clone(names[i+1:])
		if hooks.afterPublish != nil {
			if err := hooks.afterPublish(name); err != nil {
				return r, fmt.Errorf("host_init: interrupted after publishing %s: %w", name, err)
			}
		}
	}
	return r, nil
}

func initPreflightError(name string, err error) error {
	if strings.HasPrefix(err.Error(), "host_source_selection_required:") || strings.HasPrefix(err.Error(), "host_source_unavailable:") {
		return err
	}
	return fmt.Errorf("host_conflict: %s: %w", name, err)
}

func safePath(root, target string) error {
	rel, err := filepath.Rel(root, target)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return fmt.Errorf("host_path_outside_root")
	}
	current := root
	for _, part := range strings.Split(rel, string(filepath.Separator)) {
		current = filepath.Join(current, part)
		info, err := os.Lstat(current)
		if os.IsNotExist(err) {
			continue
		}
		if err != nil {
			return err
		}
		if info.Mode()&os.ModeSymlink != 0 {
			return fmt.Errorf("host_symlink: %s", current)
		}
		if !info.IsDir() && !info.Mode().IsRegular() {
			return fmt.Errorf("host_special_file: %s", current)
		}
	}
	return nil
}
func mergeBlock(before, block []byte, start, end, name string) ([]byte, error) {
	starts := bytes.Count(before, []byte(start))
	ends := bytes.Count(before, []byte(end))
	if starts == 0 && ends == 0 {
		after := append([]byte(nil), before...)
		if len(after) > 0 && after[len(after)-1] != '\n' {
			after = append(after, '\n')
		}
		if len(after) > 0 {
			after = append(after, '\n')
		}
		return append(after, block...), nil
	}
	if starts != 1 || ends != 1 {
		return nil, fmt.Errorf("managed block differs or is malformed")
	}
	startAt := bytes.Index(before, []byte(start))
	endAt := bytes.Index(before, []byte(end))
	if endAt < startAt {
		return nil, fmt.Errorf("managed block differs or is malformed")
	}
	endAt += len(end)
	if endAt >= len(before) || before[endAt] != '\n' {
		return nil, fmt.Errorf("managed block differs or is malformed")
	}
	endAt++
	oldBlock := before[startAt:endAt]
	if bytes.Equal(oldBlock, block) {
		return append([]byte(nil), before...), nil
	}
	if !knownPriorGenerated(name, oldBlock) {
		return nil, fmt.Errorf("managed block differs or is malformed")
	}
	after := append([]byte(nil), before[:startAt]...)
	after = append(after, block...)
	after = append(after, before[endAt:]...)
	return after, nil
}

// Merge only table-oriented TOML we can establish is outside our table family.
// Inline root mcp_servers, multiline values and escaped keys require manual
// preparation; rejection leaves all files unchanged rather than guessing a merge.
func checkTOML(raw []byte) error {
	parent := ""
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.Contains(line, "\"\"\"") || strings.Contains(line, "'''") {
			return fmt.Errorf("host_conflict: multiline TOML requires manual preparation")
		}
		if strings.HasPrefix(line, "[") {
			end := strings.Index(line, "]")
			if end < 0 {
				return fmt.Errorf("host_conflict: unsupported TOML table")
			}
			key, err := tomlKey(strings.Trim(line[1:end], "[]"))
			if err != nil {
				return err
			}
			parent = key
			if key == "mcp_servers.haft10" || strings.HasPrefix(key, "mcp_servers.haft10.") {
				return fmt.Errorf("host_conflict: mcp_servers.haft10 already exists outside managed block")
			}
		} else {
			key, _, ok := strings.Cut(line, "=")
			if !ok {
				return fmt.Errorf("host_conflict: unsupported multiline TOML")
			}
			key, err := tomlKey(strings.TrimSpace(key))
			if err != nil {
				return err
			}
			if parent != "" {
				key = parent + "." + key
			}
			if key == "mcp_servers" || key == "mcp_servers.haft10" || strings.HasPrefix(key, "mcp_servers.haft10.") {
				return fmt.Errorf("host_conflict: MCP key requires manual preparation")
			}
		}
	}
	return nil
}
func tomlKey(s string) (string, error) {
	parts := strings.Split(s, ".")
	for i, p := range parts {
		p = strings.TrimSpace(p)
		if strings.HasPrefix(p, "\"") {
			v, err := strconv.Unquote(p)
			if err != nil {
				return "", fmt.Errorf("host_conflict: unsupported quoted TOML key")
			}
			p = v
		} else if strings.HasPrefix(p, "'") && strings.HasSuffix(p, "'") {
			p = strings.Trim(p, "'")
		}
		if p == "" || strings.ContainsAny(p, "\"'[]\\") {
			return "", fmt.Errorf("host_conflict: unsupported TOML key")
		}
		parts[i] = p
	}
	return strings.Join(parts, "."), nil
}
