package host

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const configStart = "# haft10:start"
const configEnd = "# haft10:end"

type managedConfig struct {
	Root             string
	Binary           string
	SourceRoot       string
	SourceRepository string
	Profile          string
}

func (c managedConfig) block() []byte {
	args := []string{"serve", "--root", c.Root}
	if c.SourceRoot != "" {
		args = append(args, "--source-root", c.SourceRoot)
	}
	if c.SourceRepository != "" {
		args = append(args, "--source-repository", c.SourceRepository)
	}
	if c.Profile == "legacy" {
		args = append(args, "--profile", c.Profile)
	}
	command, _ := json.Marshal(c.Binary)
	argv, _ := json.Marshal(args)
	text := configStart + "\n[mcp_servers.haft10]\ncommand = " + string(command) + "\nargs = " + string(argv) + "\n" + configEnd + "\n"
	return []byte(text)
}

// The previous init wrote a canonical block, but no ownership receipt. A
// dynamic address that still has this exact generated shape is indistinguishable
// from an operator's address edit; all other edits are rejected before writing.
func parseManagedConfig(block []byte) (managedConfig, error) {
	var c managedConfig
	lines := strings.Split(string(block), "\n")
	if len(lines) != 6 || lines[0] != configStart || lines[1] != "[mcp_servers.haft10]" || lines[4] != configEnd || lines[5] != "" {
		return c, fmt.Errorf("managed config is not an exact Haft-generated block")
	}
	command, ok := strings.CutPrefix(lines[2], "command = ")
	if !ok {
		return c, fmt.Errorf("managed config command was edited")
	}
	argsText, ok := strings.CutPrefix(lines[3], "args = ")
	if !ok {
		return c, fmt.Errorf("managed config arguments were edited")
	}
	var args []string
	if err := json.Unmarshal([]byte(command), &c.Binary); err != nil {
		return c, fmt.Errorf("managed config command is not a generated JSON string")
	}
	if err := json.Unmarshal([]byte(argsText), &args); err != nil {
		return c, fmt.Errorf("managed config arguments are not a generated JSON array")
	}
	if !filepath.IsAbs(c.Binary) || len(args) < 3 || args[0] != "serve" || args[1] != "--root" || !filepath.IsAbs(args[2]) {
		return c, fmt.Errorf("managed config has an unsupported binary or project root")
	}
	c.Root = args[2]
	args = args[3:]
	if len(args) >= 2 && args[0] == "--source-root" && filepath.IsAbs(args[1]) {
		c.SourceRoot = args[1]
		args = args[2:]
	}
	if len(args) >= 2 && args[0] == "--source-repository" && args[1] != "" {
		c.SourceRepository = args[1]
		args = args[2:]
	}
	if len(args) == 2 && args[0] == "--profile" && args[1] == "legacy" {
		c.Profile = "legacy"
		args = args[2:]
	}
	if len(args) != 0 || !bytes.Equal(block, c.block()) {
		return c, fmt.Errorf("managed config has unsupported fields or edited generated bytes")
	}
	return c, nil
}

func managedSlice(raw []byte, start, end string) (int, int, []byte, []byte, error) {
	startMark := []byte(start)
	endMark := []byte(end)
	if bytes.Count(raw, startMark) != 1 || bytes.Count(raw, endMark) != 1 {
		return 0, 0, nil, nil, fmt.Errorf("managed block differs or is malformed")
	}
	startAt := bytes.Index(raw, startMark)
	endAt := bytes.Index(raw, endMark)
	if endAt < startAt {
		return 0, 0, nil, nil, fmt.Errorf("managed block differs or is malformed")
	}
	endAt += len(endMark)
	if endAt >= len(raw) || raw[endAt] != '\n' {
		return 0, 0, nil, nil, fmt.Errorf("managed block differs or is malformed")
	}
	endAt++
	block := bytes.Clone(raw[startAt:endAt])
	outside := append(bytes.Clone(raw[:startAt]), raw[endAt:]...)
	return startAt, endAt, block, outside, nil
}

func mergeManagedConfig(before []byte, next managedConfig) ([]byte, error) {
	startCount := bytes.Count(before, []byte(configStart))
	endCount := bytes.Count(before, []byte(configEnd))
	if startCount == 0 && endCount == 0 {
		if err := checkTOML(before); err != nil {
			return nil, err
		}
		return mergeBlock(before, next.block(), configStart, configEnd, ".codex/config.toml")
	}
	startAt, endAt, oldBlock, _, err := managedSlice(before, configStart, configEnd)
	if err != nil {
		return nil, err
	}
	prior, err := parseManagedConfig(oldBlock)
	if err != nil {
		return nil, err
	}
	if err := checkTOML(before[:startAt]); err != nil {
		return nil, err
	}
	if err := checkTOMLAfterManagedBlock(before[endAt:]); err != nil {
		return nil, err
	}
	if next.SourceRoot == "" {
		changedRoot := !sameProjectRoot(prior.Root, next.Root)
		inheritedInside := prior.SourceRoot != "" && sourceWithinProject(prior.SourceRoot, prior.Root)
		if changedRoot && inheritedInside {
			return nil, fmt.Errorf("host_source_selection_required: %s; the inherited source belongs to the prior project root. prior source %q; prior root %q; current root %q", sourceRootRecovery, prior.SourceRoot, prior.Root, next.Root)
		}
		if prior.SourceRoot != "" {
			inherited, err := inheritedSourceTarget(prior.SourceRoot)
			if err != nil {
				return nil, err
			}
			next.SourceRoot = inherited
		}
	}
	if next.SourceRepository == "" {
		next.SourceRepository = prior.SourceRepository
	}
	if next.SourceRoot != "" {
		info, statErr := os.Stat(next.SourceRoot)
		if statErr != nil || !info.IsDir() {
			return nil, fmt.Errorf("host_source_unavailable: %s; the selected source is unavailable. source %q", sourceRootRecovery, next.SourceRoot)
		}
	}
	next.Profile = prior.Profile
	after := bytes.Clone(before[:startAt])
	after = append(after, next.block()...)
	after = append(after, before[endAt:]...)
	return after, nil
}

// T02's generated addresses are physical paths. Older generated addresses can
// contain symlinks. The recorded path is a conservative fallback if the old
// project root has moved and its filesystem identity cannot be compared.
func sameProjectRoot(prior, next string) bool {
	priorInfo, priorErr := os.Stat(prior)
	nextInfo, nextErr := os.Stat(next)
	if priorErr == nil && nextErr == nil {
		return os.SameFile(priorInfo, nextInfo)
	}
	return filepath.Clean(prior) == filepath.Clean(next)
}

// Reuse the actual source reached by an older generated symlink address.
// Verify both addresses still identify the same directory before persisting it.
func inheritedSourceTarget(source string) (string, error) {
	physical, err := filepath.EvalSymlinks(source)
	if err != nil {
		return "", fmt.Errorf("host_source_unavailable: %s; the inherited source is unavailable. source %q: %w", sourceRootRecovery, source, err)
	}
	addressInfo, addressErr := os.Stat(source)
	physicalInfo, physicalErr := os.Stat(physical)
	if addressErr != nil || physicalErr != nil || !addressInfo.IsDir() || !physicalInfo.IsDir() {
		return "", fmt.Errorf("host_source_unavailable: %s; the inherited source is unavailable. source %q", sourceRootRecovery, source)
	}
	if !os.SameFile(addressInfo, physicalInfo) {
		return "", fmt.Errorf("host_source_selection_required: %s; the inherited source address and resolved target differ. source %q; target %q", sourceRootRecovery, source, physical)
	}
	return physical, nil
}

func physicalOrRecordedPath(path string) string {
	physical, err := filepath.EvalSymlinks(path)
	if err == nil {
		return physical
	}
	return filepath.Clean(path)
}

func sourceWithinProject(source, root string) bool {
	physicalSource, sourceErr := filepath.EvalSymlinks(source)
	rootInfo, rootErr := os.Stat(root)
	if sourceErr == nil && rootErr == nil {
		return hasAncestorIdentity(physicalSource, rootInfo)
	}
	physicalRoot := physicalOrRecordedPath(root)
	physicalSource = physicalOrRecordedPath(source)
	relative, err := filepath.Rel(physicalRoot, physicalSource)
	if err != nil {
		return false
	}
	return relative == "." || (relative != ".." && !strings.HasPrefix(relative, ".."+string(filepath.Separator)))
}

func hasAncestorIdentity(path string, rootInfo os.FileInfo) bool {
	for {
		candidateInfo, err := os.Stat(path)
		if err == nil && os.SameFile(candidateInfo, rootInfo) {
			return true
		}
		parent := filepath.Dir(path)
		if path == parent {
			return false
		}
		path = parent
	}
}

// A bare TOML key after the closing marker is still part of the haft10 table.
// The next foreign settings must open their own table first.
func checkTOMLAfterManagedBlock(suffix []byte) error {
	for _, line := range strings.Split(string(suffix), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if !strings.HasPrefix(line, "[") {
			return fmt.Errorf("host_conflict: key after managed block still belongs to mcp_servers.haft10; move it into an explicit foreign table")
		}
		return checkTOML(suffix)
	}
	return nil
}
